module.exports = {
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '^@/(.+)': '<rootDir>/src/$1',
    '^@/assets/illustrations/(.+.svg)$': '<rootDir>/path/to/identity-obj-proxy',
  },
  transform: {
    '^.+\\.[jt]sx?$': 'ts-jest',
    '^.+\\.png?$': '<rootDir>/src/tools/fileMock.js',
    '^.+\\.svg$': '<rootDir>/src/tools/svgTransformer.js',
  },
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverageFrom: [
    'src/components/**/*.{js,jsx,ts,tsx}',
    'src/features/**/*.{js,jsx,ts,tsx}',
    'src/hooks/**/*.{js,jsx,ts,tsx}',
    '!src/**/index.{ts,tsx}',
    '!**/*.generated.tsx',
    '!**/apis/*',
    '!src/utils/**/*.stories.{js,jsx,ts,tsx}',
    '!src/__tests__/**/*.{js,jsx,ts,tsx}',
    '!**/node_modules/**',
    '!dist/**',
    '!/src/apollo/*',
    '!/src/utils/*',
    '!/src/tools/*',
    '!/src/xhr',
    '!/src/store/main',
    '!/src/store/actions',
    '!/src/store/reducers',
    '!/src/config/getAppConfig.ts',
  ],
  coveragePathIgnorePatterns: [
    '/src/apollo',
    '/src/utils',
    '/src/tools',
    '/src/context',
    '/src/xhr',
    '/src/store/main',
    '/src/store/actions',
    '/src/store/reducers',
  ],
}
