export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const USER_TOKEN = 'USER_TOKEN'
export const CLASS_ID = '7c2bacb1-5c1d-4f7a-a8ad-3da8e217a9e2'
export const STUDENT_ID_1 = 'STUDENT_ID_1'
export const ACTIVITY_ID_1 = 'ACTIVITY_ID_1'
